[package]
name = "cgt_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
statrs = "0.16"
clap = { version = "4.0.27", features = ["derive"] }
rand = "0.8.5"
indicatif = "0.17.7"